name: Android Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Unzip Project
      run: unzip ShopBillScanner_Android_Project.zip -d project_folder

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x project_folder/gradlew

    - name: Build with Gradle
      run: |
        cd project_folder
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: project_folder/app/build/outputs/apk/debug/app-debug.apk
